version: 2.1
orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run tests and collect coverage
          command: bundle exec rspec
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build